### ISSUE TITLE
Extensibility flow: Automatic approach to adding new scan workflow tools

### ISSUE THREAD

**Issue by penenadpi** [xlab-si/iac-scan-runner#28]
As it was mentioned on GA in Milano, it is desirable to provide the functionality that would enable intuitive method for adding new check tools to the scan workflow in future, even by end-users. Therefore, the means that would automate the tool encapsulation, integration and import steps should be provided.

**Comment by cankarm** [comment]
PAths:
* provide the developers documentation how to do that
* make a plugin service

**Comment by RedekG** [comment]
This is closed with https://github.com/xlab-si/iac-scan-runner/pull/54.
