### ISSUE TITLE
Extend the compatibility matrix with all the missing check tools

### ISSUE THREAD

**Issue by penenadpi** [xlab-si/iac-scan-runner#30]
Some of the currently integrated tools are not fully supported when it comes to advanced result visualization and compatibility matrix. Furthermore, apart from adding the tools into compatibility matrix, the output of all the checks which are not present should be parsed in order to determine the outcome: passed or problems detected.

Current progress can be summarized as follows:

![image](https://user-images.githubusercontent.com/15128554/207154707-f3ada6c0-64b4-4720-a89a-203e765a2e22.png)

**Comment by RedekG** [comment]
This is resolved.
