### ISSUE TITLE
Duplicates in compatibility list (cloc, git-secret, git-leaks)

### ISSUE THREAD

**Issue by penenadpi** [xlab-si/iac-scan-runner#52]
While evaluating the list of compatible checks, aggregation from compatibility matrix is done, but duplicates for the following check: git-leaks, git-secrets. However, each of the checks should be reported exactly once.

**Comment by RedekG** [comment]
This is not a problem anymore since results present clock, git-secret and git-leaks exactly once. Closing the issue.
