### ISSUE TITLE
Resolve problems with checks (ShellCheck, hadolint, pylint)

### ISSUE THREAD

**Issue by anzoman** [xlab-si/iac-scan-runner#6]
Currently we are experiencing the following problems with checks that are part of IaC Scan Runner:

* ShellCheck does not find schell scripts
* hadolint does not find Dockerfiles (but terrascan does?!)
* pylint complains about not finding `__init__.py`

**Comment by jenkoj** [comment]
Terrascan static code analyzer returns not found error
`"/bin/sh: 1: /iac-scan-runner/tools/terrascan: not found\n"`

To replicate this error run:
`curl -X 'POST' 'http://127.0.0.1:8080/scan' -H 'Content-Type: multipart/form-data' -F 'iac=@test_tf_hw.zip' -F 'checks=terrascan'`

Used the same cmd and .zip file on `tflint` and `tfsec` and it works perfectly fine.

**Comment by jenkoj** [comment]
> @penenadpi can you confirm that these have been resolved. If so we can close this issue.

@anzoman problems above persist.

**Comment by penenadpi** [comment]
The issues are not resolved, we will be working to solve them as soon as possible.
